const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
const path=require('node:path')

const componentDir=path.resolve(__dirname,'../../miniprogram/components/loading-stage')
const read=name=>fs.readFileSync(path.join(componentDir,name),'utf8')

test('loading stage temporarily hides the gray fox but keeps text and compact mode',()=>{
  const js=read('index.js')
  const wxml=read('index.wxml')
  const wxss=read('index.wxss')
  const asset=path.resolve(componentDir,'../../assets/images/loading-gray-fox.gif')
  assert.match(js,/compact:\{type:Boolean,value:false\}/)
  assert.match(wxml,/class="loading \{\{compact \? 'compact' : ''\}\}"/)
  assert.match(wxml,/class="loading-copy"/)
  assert.doesNotMatch(wxml,/<image|loading-gray-fox\.gif|loading-fox/)
  assert.doesNotMatch(wxss,/\.loading-fox/)
  assert.equal(fs.readFileSync(asset).subarray(0,3).toString(),'GIF')
})
